<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYXxquxL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYXxquxL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYXxquxL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYXxquxL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYXxquxL\App_KernelDevDebugContainer([
    'container.build_hash' => 'YXxquxL',
    'container.build_id' => '2d4e1f0d',
    'container.build_time' => 1714999526,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYXxquxL');
